[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
magicEnabled = false
fastReruns = true

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
EOF < /dev/null
